name: Remote Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CTEST_OUTPUT_ON_FAILURE: On
  IS_GITHUB_WORKFLOW: On

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Archive
        run: tar -cvf build.tar.gz build & tar -C tests -cvf e2e.tar.gz e2e
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-archive
          path: build.tar.gz
      - name: Upload E2E Testing Infrastructure Artifact
        uses: actions/upload-artifact@v2
        with:
          name: e2e-archive
          path: e2e.tar.gz
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '3.x' 
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-archive
      - name: Download E2E Testing Infrastructure Artifact
        uses: actions/download-artifact@v2
        with:
          name: e2e-archive
      - name: Unpack
        run: tar -xvf build.tar.gz & tar -xvf e2e.tar.gz
      - name: Unit Test
        working-directory: build
        run: ctest -C ${{env.BUILD_TYPE}}
      - name: E2E Test
        working-directory: ${{github.workspace}}/e2e
        run: python3 e2e-runner.py ../build/HelloWorld
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-archive
      - name: Unpack
        run: tar -xvf build.tar.gz
      - name: Release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/HelloWorld
